name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_environment_variables: true

    - name: Authenticate Docker with gcloud
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world-nodejs .

    - name: Push Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world-nodejs:latest

    - name: Set IMAGE_URI and DIGEST
      id: image_info
      run: |
        IMAGE_URI=gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world-nodejs:latest
        DIGEST=$(gcloud container images describe $IMAGE_URI --format='value(image_summary.fully_qualified_digest)')
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV

    - name: Fetch vulnerability report using gcloud
      run: |
        gcloud container images describe ${{ env.IMAGE_URI }} --format=json > image_info.json
        IMAGE_DIGEST=$(jq -r '.image_summary.fully_qualified_digest' image_info.json)
        RESOURCE_URL="https://gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-world-nodejs@$IMAGE_DIGEST"
        FILTER="resourceUrl=\"$RESOURCE_URL\" AND kind=\"VULNERABILITY\""
        gcloud container analysis notes occurrences list \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --filter="$FILTER" \
          --format=json > vulnerability_report.json
        cat vulnerability_report.json

    - name: Upload vulnerability report
      uses: actions/upload-artifact@v2
      with:
        name: vulnerability-report
        path: vulnerability_report.json
        if-no-files-found: warn
