name: Build, Scan, and Upload Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Configure Docker
      run: |
        gcloud auth configure-docker me-west1-docker.pkg.dev
    - name: Build Docker image
      run: |
        docker build -t me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-world-nodejs/hello-world-nodejs:latest .
    - name: Push Docker image
      run: |
        docker push me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-world-nodejs/hello-world-nodejs:latest
    - name: Wait for v-report
      run: sleep 120
        
    - name: Debug IMAGE_URI and DIGEST
      run: |
        IMAGE_URI=me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-world-nodejs/hello-world-nodejs:latest
        echo "IMAGE_URI: $IMAGE_URI"
        DIGEST=$(gcloud container images describe $IMAGE_URI --format='value(image_summary.fully_qualified_digest)')
        echo "DIGEST: $DIGEST"
    - name: Export Vulnerability Report
      run: |
        IMAGE_URI=me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-world-nodejs/hello-world-nodejs:latest
        DIGEST=$(gcloud container images describe $IMAGE_URI --format='value(image_summary.fully_qualified_digest)')
        PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
        ACCESS_TOKEN=$(gcloud auth print-access-token)
        RESOURCE_URL="https://me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-world-nodejs/hello-world-nodejs@$DIGEST"
        FILTER="resourceUrl=\"$RESOURCE_URL\" AND kind=\"VULNERABILITY\""
        ENCODED_FILTER=$(jq -sRr @uri <<< "$FILTER")
        echo "Fetching vulnerability report..."
        echo "Request URL: https://containeranalysis.googleapis.com/v1/projects/$PROJECT_ID/occurrences?filter=$ENCODED_FILTER"
        echo 'IMAGE_URI' $IMAGE_URI
        echo 'DIGEST' $DIGEST
        echo 'PROJECT_ID' $PROJECT_ID
        echo 'RESOURCE_URL' $RESOURCE_URL
        echo 'FILTER' $FILTER
        
        RESPONSE=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" "https://containeranalysis.googleapis.com/v1/projects/$PROJECT_ID/occurrences?filter=$ENCODED_FILTER")
        echo "API Response: $RESPONSE" > vulnerability_report.json
        echo $RESPONSE | jq '.' >> vulnerability_report.json
        cat vulnerability_report.json
    - name: Upload Vulnerability Report
      uses: actions/upload-artifact@v2
      with:
        name: vulnerability-report
        path: vulnerability_report.json
